# Generated by Django 4.2 on 2023-04-29 16:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunnies', '0004_alter_rabbithole_latitude_alter_rabbithole_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbithole',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
